spring:
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/address_book
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate.ddl-auto: create
  data:
    jpa.repositories.bootstrap-mode: default
  sql:
    init.mode: always # always/never